export const state = {
  contacts: [],
  // contacts: [
  //   {
  //     id: 1,
  //     customer: "Test Test1",
  //     phone: "123-123",
  //     website: "test.com",
  //     company: "Test Inc.",
  //     status: "Info",
  //   },
  //   {
  //     id: 2,
  //     customer: "Test Test2",
  //     phone: "123-123",
  //     website: "test.com",
  //     company: "Test Inc.",
  //     status: "Pending",
  //   },
  //   {
  //     id: 3,
  //     customer: "Test Test3",
  //     phone: "123-123",
  //     website: "test.com",
  //     company: "Test Inc.",
  //     status: "Canceled",
  //   },
  //   {
  //     id: 4,
  //     customer: "Test Test4",
  //     phone: "123-123",
  //     website: "test.com",
  //     company: "Test Inc.",
  //     status: "Delivered",
  //   },
  //   {
  //     id: 5,
  //     customer: "Test Test5",
  //     phone: "123-123",
  //     website: "test.com",
  //     company: "Test Inc.",
  //     status: "Danger",
  //   },
  // ],
};
